name: Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies
        run: npm install
      - name: Build Code
        run: npm run build
      - name: Install Playwright Browser
        run: npx playwright install chrome
      - name: Install Browser Extension
        run: npm run setup
      - name: Run All Tests
        run: xvfb-run npm test
